// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using ToolFinder.Api.Data;

#nullable disable

namespace ToolFinder.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ToolFinder.Api.Models.CheckoutLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CheckedInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CheckedOutAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReturnedToLocationId")
                        .HasColumnType("integer");

                    b.Property<int>("ToolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReturnedToLocationId");

                    b.HasIndex("ToolId");

                    b.ToTable("CheckoutLogs");
                });

            modelBuilder.Entity("ToolFinder.Api.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ParentLocationId")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentLocationId");

                    b.HasIndex("QrCode")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ToolFinder.Api.Models.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BarcodeId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("CurrentLocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("HandwrittenId")
                        .HasColumnType("text");

                    b.Property<bool>("IsCheckedOut")
                        .HasColumnType("boolean");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "DisplayName", "Description" });

                    b.Property<string>("UpcCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeId")
                        .IsUnique();

                    b.HasIndex("CurrentLocationId");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("ToolFinder.Api.Models.CheckoutLog", b =>
                {
                    b.HasOne("ToolFinder.Api.Models.Location", "ReturnedToLocation")
                        .WithMany()
                        .HasForeignKey("ReturnedToLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ToolFinder.Api.Models.Tool", "Tool")
                        .WithMany("CheckoutLogs")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReturnedToLocation");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("ToolFinder.Api.Models.Location", b =>
                {
                    b.HasOne("ToolFinder.Api.Models.Location", "ParentLocation")
                        .WithMany("Children")
                        .HasForeignKey("ParentLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("ToolFinder.Api.Models.Tool", b =>
                {
                    b.HasOne("ToolFinder.Api.Models.Location", "CurrentLocation")
                        .WithMany("Tools")
                        .HasForeignKey("CurrentLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentLocation");
                });

            modelBuilder.Entity("ToolFinder.Api.Models.Location", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Tools");
                });

            modelBuilder.Entity("ToolFinder.Api.Models.Tool", b =>
                {
                    b.Navigation("CheckoutLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
